# Production environment configuration
spring:
  jpa:
    hibernate:
      ddl-auto: validate  # Production environment uses validate, does not auto-create tables
    show-sql: false  # Production environment disables SQL logging
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false


  # Logging configuration
  output:
    ansi:
      enabled: never  # Production environment disables colored logging

# Log level configuration
logging:
  level:
    root: INFO
    com.jobtracker: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/jobtracker/application.log


# JWT配置
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24 hours

# Application configuration
app:
  internal-api-key: ${APP_INTERNAL_API_KEY}

# AI service configuration
ai:
  service:
    url: ${AI_SERVICE_URL:http://ai_service:5000}

# WebClient configuration
web:
  client:
    base:
      url: ${WEB_CLIENT_BASE_URL:http://localhost:8000}

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true